// import { Geist, Geist_Mono } from "next/font/google";
import { Roboto, Anton } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav/header";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Nav />
//         {children}
//       </body>
//     </html>
//   );
// }

const roboto = Roboto({
  weight: ["900", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const anton = Anton({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-anton",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* ❗ YAHAN APPLY KARNA ZAROORI HAI */}
      <body className={`${roboto.variable} ${anton.variable}`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
